name = "RandomBooleanMatrices"
uuid = "9ae346a0-3d16-5633-ad70-ddb60ab77eac"
license = "MIT"
authors = ["mkborregaard <mkborregaard@snm.ku.dk"]
version = "0.1.2"

[deps]
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"
RandomNumbers = "1"
StatsBase = "0.33, 0.34"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
